# Generated by Django 5.1.1 on 2024-09-30 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="The title of the event.", max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(help_text="A detailed description of the event.", verbose_name="description"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text="The date and time when the event will take place.", verbose_name="date"
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(
                        default=False, help_text="Indicates if the event is remote.", verbose_name="remote"
                    ),
                ),
                (
                    "event_url",
                    models.URLField(
                        blank=True, help_text="URL of the event's page.", null=True, verbose_name="event URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the event was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the event was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        help_text="The organizer of the event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["date"],
            },
        ),
    ]
