databases:
  - name: techtalks-db
    plan: free
    databaseName: techtalks
    user: techtalks

services:
  - type: web
    plan: free
    name: techtalks-api
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: techtalks-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

  - type: web
    plan: free
    name: techtalks-ui
    runtime: node
    rootDir: frontend
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run preview --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        value: https://techtalks-api.onrender.com
