# Generated by Django 5.1.1 on 2024-10-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"ordering": ["event__title"], "verbose_name": "coupon", "verbose_name_plural": "coupons"},
        ),
    ]
