# Generated by Django 5.1.1 on 2024-09-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "company_name",
                    models.CharField(
                        error_messages={"unique": "A company with that name already exists."},
                        max_length=100,
                        unique=True,
                        verbose_name="company name",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ("phone", models.CharField(max_length=15, verbose_name="telephone")),
                (
                    "cnpj",
                    models.CharField(
                        error_messages={"unique": "A company with that CNPJ already exists."},
                        max_length=18,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
