# Generated by Django 5.1.1 on 2024-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="email address"),
        ),
    ]
