# Generated by Django 5.1.1 on 2024-09-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0003_organizer_groups_organizer_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizer",
            options={"ordering": ["id"]},
        ),
    ]
