# Generated by Django 5.1.1 on 2024-09-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0004_alter_organizer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="company_name",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A company with that name already exists."},
                max_length=100,
                null=True,
                unique=True,
                verbose_name="company name",
            ),
        ),
    ]
