# Generated by Django 5.1.1 on 2024-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0005_alter_organizer_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="cnpj",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A company with that CNPJ already exists."},
                max_length=18,
                null=True,
                unique=True,
                verbose_name="CNPJ",
            ),
        ),
    ]
