# Generated by Django 5.1.1 on 2024-09-29 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0007_alter_organizer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
        ),
    ]
